version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db
      - mailpit
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=zaprod_db
      - DB_USERNAME=zaprod_user
      - DB_PASSWORD=Zaprod123
    expose:
      - "9000"  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    environment:
      - NGINX_HOST=localhost
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: zaprod_user
      POSTGRES_PASSWORD: Zaprod123
      POSTGRES_DB: zaprod_db
    ports:
      - "5433:5432"
    volumes:
      - zaprod_postgres_data:/var/lib/postgresql/data
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_MAX_MESSAGES: 5000
volumes:
  zaprod_postgres_data:
