version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: "${UID}:${GID}"
    volumes:
      - .:/var/www/html
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=ihousi
      - DB_USERNAME=postgres
      - DB_PASSWORD=Ihousi101
    command: php artisan serve --host=0.0.0.0 --port=8080
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ihousi101
      POSTGRES_DB: ihousi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
