version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: "1000:1000"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5433
      - DB_DATABASE=zaprod_db
      - DB_USERNAME=zaprod_user
      - DB_PASSWORD=Zaprod123
    expose:
      - "9000"  
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    environment:
      - NGINX_HOST=localhost
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: zaprod_user
      POSTGRES_PASSWORD: Zaprod123
      POSTGRES_DB: zaprod_db
    ports:
      - "5433:5432"
    volumes:
      - zaprod_postgres_data:/var/lib/postgresql/data

volumes:
  zaprod_postgres_data:
