
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres 
      - DB_PASSWORD=postgres 
      - DB_SCHEMA=public
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    environment:
      - NGINX_HOST=localhost

  db:
    image: supabase/postgres:15.8.1.020
    container_name: supabase-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
      - ./volumes/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  studio:
    image: supabase/studio:20250113-83c9420
    depends_on:
      db:
        condition: service_healthy
    environment:
      STUDIO_PG_META_URL: http://pg-meta:8080
      SUPABASE_PUBLIC_URL: http://localhost:3000
    ports:
      - "3000:3000"
  pg-meta:
    image: supabase/postgres-meta:v0.84.2
    environment:
      PG_META_DB_HOST: supabase-db
      PG_META_DB_PORT: 5432
      PG_META_DB_NAME: postgres
      PG_META_DB_USER: postgres
      PG_META_DB_PASSWORD: postgres
      PG_META_SSL_MODE: disable
    ports:
      - "8081:8080"
    depends_on:
      - db
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_MAX_MESSAGES: 5000

volumes:
  n8n_data:
  supabase_data:
